name: Build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -workspace ./CPUThrottlingMonitor.xcodeproj/project.xcworkspace -scheme CPUThrottlingMonitor -configuration Release -allowProvisioningUpdates
    - name: Test
      run: xcodebuild -workspace ./CPUThrottlingMonitor.xcodeproj/project.xcworkspace -scheme CPUThrottlingMonitor -configuration Release -allowProvisioningUpdates test
